{{-- resources/views/invoices/dynamic.blade.php --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice {{ $invoice->invoice_number ?? 'INV-0001' }}</title>

    {{-- Google Font (dompdf supports basic fonts, so we use safe fallbacks) --}}
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: {{ $template->font_family ?? 'DejaVu Sans' }}, sans-serif;
            font-size: 13px;
            color: #333;
            background: #fff;
            padding: 40px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>

    {{-- Loop through blocks sorted by position, skip hidden ones --}}
    @foreach($blocks as $block)

        @php
            $blockId = $block['id']; // e.g. 'header', 'bill_to', 'items'
            $viewPath = 'invoices.blocks.' . $blockId;
        @endphp

        @if(view()->exists($viewPath))
            <div style="margin-bottom: 20px;">
                @include($viewPath, [
                    'invoice'  => $invoice,
                    'template' => $template,
                    'fields'   => $fields,
                ])
            </div>
        @endif

    @endforeach

    {{-- Footer --}}
    <div style="
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        text-align: center;
        font-size: 10px;
        color: #aaa;
        border-top: 1px solid #eee;
        padding: 8px 40px;
    ">
        Generated by {{ config('app.name') }} &bull; Page <span class="pagenum"></span>
    </div>

</body>
</html>